test: debug child process with title
dai-shi/waku pull request #335
Opened 2024-01-01 09:06 UTC by himself65

2024-01-01 09:23 UTC, himself65 commented
CI flaky might related to: https://github.com/actions/download-artifact/issues/249

2024-01-01 10:33 UTC, himself65 commented on e2e/utils.ts
> +  /^Warning: Expected server HTML to contain a matching/,
I noticed that there are some hydration mismatch in current CI

2024-01-01 14:42 UTC, dai-shi commented on packages/waku/src/lib/renderers/html-renderer.ts
> +  }
Is this only for our monorepo setup?

2024-01-01 14:54 UTC, himself65 commented on packages/waku/src/lib/renderers/html-renderer.ts
> +  }
I think so, but cannot find why

2024-01-01 15:14 UTC, himself65 commented
I guess this only happened in Monorepo. So, if it possible we change the way of writing examples?

Or this is still some corner case on Windows

2024-01-01 16:48 UTC, himself65 commented
Ok, the real bug is `/` on prefix again

2024-01-01 17:02 UTC, himself65 commented
![image](https://github.com/dai-shi/waku/assets/14026360/68f9b35a-16fd-46b9-9ff9-b0d474e1994a)
![image](https://github.com/dai-shi/waku/assets/14026360/f3670a3c-9013-46c6-bc8a-50ede84058d4)

2024-01-01 23:03 UTC, dai-shi requested changes

2024-01-01 23:03 UTC, dai-shi commented on packages/waku/src/lib/utils/path.ts
>  // for filePath
joinPath is only for "filePath" style. Please do not modify for multiple path styles. We should adjust it in advance. This makes things more maintainable.

2024-01-02 23:45 UTC, dai-shi approved these changes
LGTM!

2024-01-03 00:10 UTC, merged