fix: non js assets path should add / to be relative to root path
dai-shi/waku pull request #697
Opened 2024-05-04 16:59 UTC by PerfectPan

Solve https://github.com/dai-shi/waku/issues/649.

I did some research based on https://github.com/dai-shi/waku/pull/674. The root cause is that css path in html missing / so that when brower try to join the real path, it will use the current path instead of root path.

![CleanShot 2024-05-05 at 00 44 55@2x](https://github.com/dai-shi/waku/assets/24316656/55ac214d-b5c9-49ed-9e67-95b59ed837b8)

![CleanShot 2024-05-05 at 00 45 27@2x](https://github.com/dai-shi/waku/assets/24316656/40021aeb-acbe-4f07-ac9f-79e9d7ebaa2a)

2024-05-04 23:21 UTC, dai-shi requested changes
Thanks for investigating into it! It looks valid.
We use `basePath` instead of `/`. (Though, we don't have tests and changing basePath in config might not fully work, yet. Contributions are welcome.)

2024-05-04 23:21 UTC, dai-shi commented on packages/waku/src/lib/plugins/vite-plugin-rsc-index.ts
> +          attrs: { rel: 'stylesheet', href: `/${href}` },
```suggestion
          attrs: { rel: 'stylesheet', href: `${opts.basePath}${href}` },
```

2024-05-04 23:21 UTC, dai-shi commented on packages/waku/src/lib/builder/build.ts
> +            .map((asset) => `<link rel="stylesheet" href="/${asset}">`)
```suggestion
            .map((asset) => `<link rel="stylesheet" href="${config.basePath}${asset}">`)
```

2024-05-05 03:02 UTC, PerfectPan commented
> Thanks for investigating into it! It looks valid. We use `basePath` instead of `/`. (Though, we don't have tests and changing basePath in config might not fully work, yet. Contributions are welcome.)

I totally ignore the basePath option lol. I have already changed the code.

For changing basePath in config, I tried and it seems not working well.

![CleanShot 2024-05-05 at 10 58 35@2x](https://github.com/dai-shi/waku/assets/24316656/ce0be051-47b5-4d98-a9a4-27d05fbc2e0a)

This may involve the paths of resources in HTML files, the paths of generated files, and the paths for server hosting static resources. It seems that something is not quite right with all of them.

Would you mind I open an another issue to follow this and try to add test cases and solution later?

2024-05-05 03:56 UTC, dai-shi commented
Yeah, we have the `basePath` config but it's never used in `cli.ts`.
(I guess it would be `app.use('/test/*', ...)`.)

Please open a PR and maybe our first target would be SSG.

2024-05-05 04:15 UTC, dai-shi approved these changes
The code looks okay.

I wonder if @Aslemammad can give a review too.

2024-05-05 05:24 UTC, Aslemammad approved these changes
Clean & Simple! I love the catch.

2024-05-05 08:06 UTC, merged