fix: build target for vercel will throw error
dai-shi/waku pull request #699
Opened 2024-05-05 08:36 UTC by PerfectPan

2024-05-05 12:54 UTC, dai-shi commented on packages/waku/src/lib/plugins/vite-plugin-rsc-serve.ts
> +        path.resolve(viteConfig.root || '.', opts.srcDir, SRC_ENTRIES),
Can you try this?
```suggestion
        path.resolve(viteConfig.root || '.', opts.srcDir, SRC_ENTRIES + '.jsx'),
```

2024-05-05 15:12 UTC, PerfectPan commented on packages/waku/src/lib/plugins/vite-plugin-rsc-serve.ts
> +        path.resolve(viteConfig.root || '.', opts.srcDir, SRC_ENTRIES),
I tried, it seems ok as well.

2024-05-05 16:10 UTC, PerfectPan commented
All the windows tests are failed. Maybe there are another issues?

2024-05-05 22:54 UTC, dai-shi commented
probably, wrap with `normalizePath`.

2024-05-06 06:07 UTC, PerfectPan commented
> probably, wrap with `normalizePath`.

Ha, you are right

2024-05-06 07:07 UTC, dai-shi approved these changes
Great it works. Thanks for your contribution!
I really appreciate it. (As noted as "FIXME", I'm not super comfortable with the current solution. Hopefully, we will revisit it.)

2024-05-06 08:23 UTC, PerfectPan commented
I see the failed test stuck on `actions/setup-node` downloading, can you rerun the test?

2024-05-06 11:01 UTC, dai-shi requested changes
Sorry, I didn't notice before. Can you try this please?

2024-05-06 11:01 UTC, dai-shi commented on e2e/multi-platform.spec.ts
> +const cwd = fileURLToPath(new URL('../examples/01_template', import.meta.url));
Can you add test with `20_minimal` too?

2024-05-06 11:29 UTC, PerfectPan commented on e2e/multi-platform.spec.ts
> +const cwd = fileURLToPath(new URL('../examples/01_template', import.meta.url));
OK

2024-05-06 12:32 UTC, dai-shi approved these changes
LGTM
Thanks for the adjustment.

2024-05-06 12:32 UTC, merged