feat: ssr middlware
dai-shi/waku pull request #74
Opened 2023-06-12 04:59 UTC by dai-shi

Close #66 

- [x] first experiment
- [ ] dev with examples/01_counter
- [ ] dev with examples/07_router
- [ ] dev with examples/*
- [ ] build and prd server
- [ ] build and static sites

2023-06-12 05:25 UTC, dai-shi commented
Found a relevant comment: https://github.com/facebook/react/issues/25627#issuecomment-1444073227

> You can suppress the error you've thrown from the console in onRecoverableError handler in your hydrateRoot options.

Let's do that.

2023-06-13 08:02 UTC, Himself65 requested changes

2023-06-13 08:02 UTC, Himself65 commented on src/lib/middleware/ssr.ts
> +        Readable.fromWeb(rscRes.body as any), // FIXME how to avoid any?
Update to `"@types/node": "^20.3.1"` could fix this issue

This is upstream bug

2023-06-19 02:24 UTC, dai-shi commented on src/lib/config.ts
> +};
I tried to create a full SSR (= also render client components into HTML on server) example, with configuring `getFallback`, but there are a few issues and I gave it up doing in this PR:
- We need a module graph in DEV, which we don't have in our current architecture.
- In production mode, it should be easier, but the configuration would be tricker.
- What's really blocking is probably as we load React in a separate worker, we get "Invalid hook call." error. I don't think we can do SSR in the same worker, so we'd need a new separate worker and duplicate the work. That doesn't feel very RSC-first framework.

We will see it again in the future, maybe after we migrate to `react-server-dom-vite`, which is not yet planned.

2023-06-19 03:09 UTC, merged

2023-06-20 01:33 UTC, dai-shi commented on examples/02_async/entries.ts
> +  // FIXME SSR streaming and RSC streaming conflict. Let's revisit it later.
I think I understand what's happening. We need to send our `<script>` in the middle of SSR streaming. Let me see how we could do that in a simple way... 🤔

2023-06-20 06:56 UTC, dai-shi commented on examples/02_async/entries.ts
> +  // FIXME SSR streaming and RSC streaming conflict. Let's revisit it later.
#78